-- QLVT asset schema init script.
--
-- Purpose:
--   Recreate the asset schema from scratch using the improved schema described in:
--   documents/luoc-do-chi-tiet-schema-qlvt.md
--
-- Important:
--   This script is destructive. It drops schema asset and all data inside it.
--   Keep it outside db/migration so Flyway does not run it automatically.
--   Use it only for local/dev database reset or initial schema bootstrap.
--   Production/staging schema changes must go through db/migration/V*.sql.

DROP SCHEMA IF EXISTS asset CASCADE;
CREATE SCHEMA asset;

-- ---------------------------------------------------------------------------
-- Master data: asset categories
-- ---------------------------------------------------------------------------

CREATE TABLE asset.asset_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(60) NOT NULL,
    name VARCHAR(180) NOT NULL,
    parent_id BIGINT NULL,
    asset_class VARCHAR(40) NOT NULL,
    description VARCHAR(500) NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    updated_at TIMESTAMP NOT NULL DEFAULT now(),

    CONSTRAINT uk_asset_categories_code UNIQUE (code),
    CONSTRAINT fk_asset_categories_parent
        FOREIGN KEY (parent_id) REFERENCES asset.asset_categories(id)
        ON DELETE RESTRICT,
    CONSTRAINT ck_asset_categories_asset_class
        CHECK (asset_class IN ('FIXED_ASSET', 'TOOL_EQUIPMENT'))
);

CREATE INDEX idx_asset_categories_parent_id ON asset.asset_categories(parent_id);
CREATE INDEX idx_asset_categories_asset_class ON asset.asset_categories(asset_class);
CREATE INDEX idx_asset_categories_is_active ON asset.asset_categories(is_active);

INSERT INTO asset.asset_categories (code, name, asset_class, description)
VALUES
    ('FIXED_ASSET', 'Tài sản cố định', 'FIXED_ASSET', 'Nhóm tài sản cố định'),
    ('TOOL_EQUIPMENT', 'Công cụ dụng cụ', 'TOOL_EQUIPMENT', 'Nhóm công cụ dụng cụ');

-- INSERT INTO asset.asset_categories (code, name, parent_id, asset_class, description)
-- VALUES
--     (
--         'TANGIBLE',
--         'Tài sản hữu hình',
--         (SELECT id FROM asset.asset_categories WHERE code = 'FIXED_ASSET'),
--         'FIXED_ASSET',
--         'Máy móc, xe, khuôn mặt, nhà xưởng, vật kiến trúc'
--     ),
--     (
--         'INTANGIBLE',
--         'Tài sản vô hình',
--         (SELECT id FROM asset.asset_categories WHERE code = 'FIXED_ASSET'),
--         'FIXED_ASSET',
--         'Bản quyền phần mềm, license, quyền sử dụng, gọi dịch vụ dài hạn'
--     ),
--     (
--         'TOOL_SINGLE_USE',
--         'Công cụ dùng một lần',
--         (SELECT id FROM asset.asset_categories WHERE code = 'TOOL_EQUIPMENT'),
--         'TOOL_EQUIPMENT',
--         'Công cụ dụng cụ dùng một lần'
--     ),
--     (
--         'TOOL_MULTI_USE',
--         'Công cụ dùng nhiều lần',
--         (SELECT id FROM asset.asset_categories WHERE code = 'TOOL_EQUIPMENT'),
--         'TOOL_EQUIPMENT',
--         'Công cụ dụng cụ dùng nhiều lần'
--     );

-- ---------------------------------------------------------------------------
-- Vendors
-- ---------------------------------------------------------------------------

CREATE TABLE asset.vendors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(180) NOT NULL,
    tax_code VARCHAR(80) NULL,
    contact_name VARCHAR(120) NULL,
    phone VARCHAR(40) NULL,
    email VARCHAR(120) NULL,
    address VARCHAR(500) NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    updated_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX uk_vendors_tax_code
    ON asset.vendors(tax_code)
    WHERE tax_code IS NOT NULL;

CREATE INDEX idx_vendors_name ON asset.vendors(name);
CREATE INDEX idx_vendors_status ON asset.vendors(status);

-- ---------------------------------------------------------------------------
-- Catalog items
-- ---------------------------------------------------------------------------

CREATE TABLE asset.asset_catalog_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_code VARCHAR(80) NOT NULL,
    name VARCHAR(255) NOT NULL,
    category_id BIGINT NULL,
    catalog_type VARCHAR(40) NOT NULL,
    inventory_group VARCHAR(120) NULL,
    unit VARCHAR(40) NULL,
    cost_value NUMERIC(18,2) NULL,
    standard_value NUMERIC(18,2) NULL,
    fixed_value NUMERIC(18,2) NULL,
    internal_value NUMERIC(18,2) NULL,
    technical_spec VARCHAR(1000) NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    updated_at TIMESTAMP NOT NULL DEFAULT now(),

    CONSTRAINT uk_asset_catalog_items_item_code UNIQUE (item_code),
    CONSTRAINT fk_asset_catalog_items_category
        FOREIGN KEY (category_id) REFERENCES asset.asset_categories(id)
        ON DELETE SET NULL,
    CONSTRAINT ck_asset_catalog_items_catalog_type
        CHECK (catalog_type IN ('ASSET', 'TOOL', 'MATERIAL', 'PRODUCT_REFERENCE')),
    CONSTRAINT ck_asset_catalog_items_values_non_negative
        CHECK (
            (cost_value IS NULL OR cost_value >= 0)
            AND (standard_value IS NULL OR standard_value >= 0)
            AND (fixed_value IS NULL OR fixed_value >= 0)
            AND (internal_value IS NULL OR internal_value >= 0)
        )
);

CREATE INDEX idx_asset_catalog_items_category_id ON asset.asset_catalog_items(category_id);
CREATE INDEX idx_asset_catalog_items_catalog_type ON asset.asset_catalog_items(catalog_type);
CREATE INDEX idx_asset_catalog_items_name ON asset.asset_catalog_items(name);
CREATE INDEX idx_asset_catalog_items_is_active ON asset.asset_catalog_items(is_active);

-- ---------------------------------------------------------------------------
-- Assets
-- ---------------------------------------------------------------------------

CREATE TABLE asset.assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_code VARCHAR(80) NOT NULL,
    name VARCHAR(255) NOT NULL,
    catalog_item_id BIGINT NULL,
    category_id BIGINT NOT NULL,
    category VARCHAR(80) NULL,
    parent_asset_id BIGINT NULL,
    asset_class VARCHAR(40) NOT NULL,
    fixed_asset_type VARCHAR(40) NULL,
    tool_usage_type VARCHAR(40) NULL,
    serial_number VARCHAR(120) NULL,
    source VARCHAR(120) NULL,
    vendor_id BIGINT NULL,
    assigned_employee_id BIGINT NULL,
    department_id BIGINT NULL,
    site_id BIGINT NULL,
    project_id BIGINT NULL,
    purchase_date DATE NULL,
    use_date DATE NULL,
    depreciation_start_date DATE NULL,
    warranty_until DATE NULL,
    original_cost NUMERIC(18,2) NULL,
    purchase_cost NUMERIC(18,2) NULL,
    accumulated_depreciation NUMERIC(18,2) NOT NULL DEFAULT 0,
    book_value NUMERIC(18,2) NULL,
    residual_value NUMERIC(18,2) NULL,
    depreciation_method VARCHAR(40) NULL DEFAULT 'STRAIGHT_LINE',
    useful_life_months INTEGER NULL,
    useful_life_years INTEGER NULL,
    depreciation_rate NUMERIC(8,4) NULL,
    manufacture_year INTEGER NULL,
    installation_year INTEGER NULL,
    country_code VARCHAR(10) NULL,
    capacity NUMERIC(18,4) NULL,
    capacity_unit VARCHAR(40) NULL,
    real_capacity NUMERIC(18,4) NULL,
    technical_description VARCHAR(2000) NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'IN_STOCK',
    disposal_date DATE NULL,
    disposal_price NUMERIC(18,2) NULL,
    disposal_reason VARCHAR(500) NULL,
    notes VARCHAR(1000) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    updated_at TIMESTAMP NOT NULL DEFAULT now(),

    CONSTRAINT uk_assets_asset_code UNIQUE (asset_code),
    CONSTRAINT fk_assets_catalog_item
        FOREIGN KEY (catalog_item_id) REFERENCES asset.asset_catalog_items(id)
        ON DELETE SET NULL,
    CONSTRAINT fk_assets_category
        FOREIGN KEY (category_id) REFERENCES asset.asset_categories(id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_assets_parent_asset
        FOREIGN KEY (parent_asset_id) REFERENCES asset.assets(id)
        ON DELETE SET NULL,
    CONSTRAINT fk_assets_vendor
        FOREIGN KEY (vendor_id) REFERENCES asset.vendors(id)
        ON DELETE SET NULL,
    CONSTRAINT ck_assets_asset_class
        CHECK (asset_class IN ('FIXED_ASSET', 'TOOL_EQUIPMENT')),
    CONSTRAINT ck_assets_fixed_asset_type
        CHECK (fixed_asset_type IS NULL OR fixed_asset_type IN ('TANGIBLE', 'INTANGIBLE')),
    CONSTRAINT ck_assets_tool_usage_type
        CHECK (tool_usage_type IS NULL OR tool_usage_type IN ('SINGLE_USE', 'MULTI_USE')),
    CONSTRAINT ck_assets_fixed_asset_type_required
        CHECK (asset_class <> 'FIXED_ASSET' OR fixed_asset_type IS NOT NULL),
    CONSTRAINT ck_assets_tool_usage_type_required
        CHECK (asset_class <> 'TOOL_EQUIPMENT' OR tool_usage_type IS NOT NULL),
    CONSTRAINT ck_assets_status
        CHECK (status IN ('IN_STOCK', 'ASSIGNED', 'MAINTENANCE', 'LOST', 'DISPOSED')),
    CONSTRAINT ck_assets_depreciation_method
        CHECK (
            depreciation_method IS NULL
            OR depreciation_method IN ('STRAIGHT_LINE', 'DECLINING_BALANCE', 'NONE')
        ),
    CONSTRAINT ck_assets_money_non_negative
        CHECK (
            (original_cost IS NULL OR original_cost >= 0)
            AND (purchase_cost IS NULL OR purchase_cost >= 0)
            AND (accumulated_depreciation >= 0)
            AND (book_value IS NULL OR book_value >= 0)
            AND (residual_value IS NULL OR residual_value >= 0)
            AND (disposal_price IS NULL OR disposal_price >= 0)
        ),
    CONSTRAINT ck_assets_life_non_negative
        CHECK (
            (useful_life_months IS NULL OR useful_life_months >= 0)
            AND (useful_life_years IS NULL OR useful_life_years >= 0)
            AND (depreciation_rate IS NULL OR depreciation_rate >= 0)
        ),
    CONSTRAINT ck_assets_capacity_non_negative
        CHECK (
            (capacity IS NULL OR capacity >= 0)
            AND (real_capacity IS NULL OR real_capacity >= 0)
        )
);

CREATE INDEX idx_assets_asset_code ON asset.assets(asset_code);
CREATE INDEX idx_assets_name ON asset.assets(name);
CREATE INDEX idx_assets_catalog_item_id ON asset.assets(catalog_item_id);
CREATE INDEX idx_assets_category_id ON asset.assets(category_id);
CREATE INDEX idx_assets_category ON asset.assets(category);
CREATE INDEX idx_assets_parent_asset_id ON asset.assets(parent_asset_id);
CREATE INDEX idx_assets_asset_class ON asset.assets(asset_class);
CREATE INDEX idx_assets_status ON asset.assets(status);
CREATE INDEX idx_assets_assigned_employee_id ON asset.assets(assigned_employee_id);
CREATE INDEX idx_assets_department_id ON asset.assets(department_id);
CREATE INDEX idx_assets_site_id ON asset.assets(site_id);
CREATE INDEX idx_assets_project_id ON asset.assets(project_id);
CREATE INDEX idx_assets_vendor_id ON asset.assets(vendor_id);

-- ---------------------------------------------------------------------------
-- Value snapshots
-- ---------------------------------------------------------------------------

CREATE TABLE asset.asset_value_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id BIGINT NOT NULL,
    snapshot_date DATE NOT NULL,
    original_cost NUMERIC(18,2) NOT NULL,
    period_depreciation NUMERIC(18,2) NOT NULL DEFAULT 0,
    accumulated_depreciation NUMERIC(18,2) NOT NULL DEFAULT 0,
    book_value NUMERIC(18,2) NOT NULL,
    source VARCHAR(80) NOT NULL DEFAULT 'SYSTEM_CALCULATION',
    notes VARCHAR(500) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT now(),

    CONSTRAINT uk_asset_value_snapshots_asset_date_source
        UNIQUE (asset_id, snapshot_date, source),
    CONSTRAINT fk_asset_value_snapshots_asset
        FOREIGN KEY (asset_id) REFERENCES asset.assets(id)
        ON DELETE CASCADE,
    CONSTRAINT ck_asset_value_snapshots_source
        CHECK (source IN ('IMPORT', 'SYSTEM_CALCULATION', 'MANUAL_ADJUSTMENT')),
    CONSTRAINT ck_asset_value_snapshots_money_non_negative
        CHECK (
            original_cost >= 0
            AND period_depreciation >= 0
            AND accumulated_depreciation >= 0
            AND book_value >= 0
        )
);

CREATE INDEX idx_asset_value_snapshots_asset_id ON asset.asset_value_snapshots(asset_id);
CREATE INDEX idx_asset_value_snapshots_snapshot_date ON asset.asset_value_snapshots(snapshot_date);
CREATE INDEX idx_asset_value_snapshots_source ON asset.asset_value_snapshots(source);

-- ---------------------------------------------------------------------------
-- Asset documents
-- ---------------------------------------------------------------------------

CREATE TABLE asset.asset_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id BIGINT NOT NULL,
    document_type VARCHAR(50) NOT NULL DEFAULT 'OTHER',
    file_name VARCHAR(255) NOT NULL,
    object_key VARCHAR(500) NOT NULL,
    content_type VARCHAR(120) NULL,
    size_bytes BIGINT NULL,
    uploaded_by VARCHAR(200) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT now(),

    CONSTRAINT uk_asset_documents_object_key UNIQUE (object_key),
    CONSTRAINT fk_asset_documents_asset
        FOREIGN KEY (asset_id) REFERENCES asset.assets(id)
        ON DELETE CASCADE,
    CONSTRAINT ck_asset_documents_document_type
        CHECK (document_type IN ('IMAGE', 'HANDOVER', 'INVOICE', 'WARRANTY', 'MAINTENANCE', 'DISPOSAL', 'OTHER')),
    CONSTRAINT ck_asset_documents_size_non_negative
        CHECK (size_bytes IS NULL OR size_bytes >= 0)
);

CREATE INDEX idx_asset_documents_asset_id ON asset.asset_documents(asset_id);
CREATE INDEX idx_asset_documents_document_type ON asset.asset_documents(document_type);
CREATE INDEX idx_asset_documents_created_at ON asset.asset_documents(created_at);

-- ---------------------------------------------------------------------------
-- Asset QR codes
-- ---------------------------------------------------------------------------

CREATE TABLE asset.asset_qr_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id BIGINT NOT NULL,
    qr_payload VARCHAR(1000) NOT NULL,
    qr_token VARCHAR(120) NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    printed_at TIMESTAMP NULL,
    printed_by VARCHAR(200) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT now(),

    CONSTRAINT uk_asset_qr_codes_qr_token UNIQUE (qr_token),
    CONSTRAINT fk_asset_qr_codes_asset
        FOREIGN KEY (asset_id) REFERENCES asset.assets(id)
        ON DELETE CASCADE,
    CONSTRAINT ck_asset_qr_codes_status
        CHECK (status IN ('ACTIVE', 'REVOKED'))
);

CREATE INDEX idx_asset_qr_codes_asset_id ON asset.asset_qr_codes(asset_id);
CREATE INDEX idx_asset_qr_codes_status ON asset.asset_qr_codes(status);
CREATE INDEX idx_asset_qr_codes_qr_token ON asset.asset_qr_codes(qr_token);

-- ---------------------------------------------------------------------------
-- Asset transfers
-- ---------------------------------------------------------------------------

CREATE TABLE asset.asset_transfers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id BIGINT NOT NULL,
    transfer_type VARCHAR(30) NOT NULL,
    transfer_date DATE NOT NULL,
    from_employee_id BIGINT NULL,
    to_employee_id BIGINT NULL,
    from_department_id BIGINT NULL,
    to_department_id BIGINT NULL,
    from_site_id BIGINT NULL,
    to_site_id BIGINT NULL,
    from_project_id BIGINT NULL,
    to_project_id BIGINT NULL,
    condition_before VARCHAR(500) NULL,
    condition_after VARCHAR(500) NULL,
    reason VARCHAR(1000) NULL,
    handover_document_url VARCHAR(500) NULL,
    handover_document_id BIGINT NULL,
    performed_by VARCHAR(200) NULL,
    approved_by VARCHAR(200) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT now(),

    CONSTRAINT fk_asset_transfers_asset
        FOREIGN KEY (asset_id) REFERENCES asset.assets(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_asset_transfers_handover_document
        FOREIGN KEY (handover_document_id) REFERENCES asset.asset_documents(id)
        ON DELETE SET NULL
);

CREATE INDEX idx_asset_transfers_asset_id ON asset.asset_transfers(asset_id);
CREATE INDEX idx_asset_transfers_transfer_date ON asset.asset_transfers(transfer_date);
CREATE INDEX idx_asset_transfers_from_employee_id ON asset.asset_transfers(from_employee_id);
CREATE INDEX idx_asset_transfers_to_employee_id ON asset.asset_transfers(to_employee_id);
CREATE INDEX idx_asset_transfers_from_department_id ON asset.asset_transfers(from_department_id);
CREATE INDEX idx_asset_transfers_to_department_id ON asset.asset_transfers(to_department_id);

-- ---------------------------------------------------------------------------
-- Maintenance records
-- ---------------------------------------------------------------------------

CREATE TABLE asset.maintenance_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id BIGINT NOT NULL,
    vendor_id BIGINT NULL,
    maintenance_type VARCHAR(30) NOT NULL,
    maintenance_date DATE NOT NULL,
    next_maintenance_date DATE NULL,
    performed_by VARCHAR(200) NULL,
    description VARCHAR(1000) NULL,
    cost NUMERIC(18,2) NULL,
    downtime_hours NUMERIC(10,2) NULL,
    meter_reading NUMERIC(18,2) NULL,
    condition_after VARCHAR(500) NULL,
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    updated_at TIMESTAMP NOT NULL DEFAULT now(),

    CONSTRAINT fk_maintenance_records_asset
        FOREIGN KEY (asset_id) REFERENCES asset.assets(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_maintenance_records_vendor
        FOREIGN KEY (vendor_id) REFERENCES asset.vendors(id)
        ON DELETE SET NULL,
    CONSTRAINT ck_maintenance_records_numbers_non_negative
        CHECK (
            (cost IS NULL OR cost >= 0)
            AND (downtime_hours IS NULL OR downtime_hours >= 0)
            AND (meter_reading IS NULL OR meter_reading >= 0)
        )
);

CREATE INDEX idx_maintenance_records_asset_id ON asset.maintenance_records(asset_id);
CREATE INDEX idx_maintenance_records_vendor_id ON asset.maintenance_records(vendor_id);
CREATE INDEX idx_maintenance_records_maintenance_date ON asset.maintenance_records(maintenance_date);
CREATE INDEX idx_maintenance_records_next_maintenance_date ON asset.maintenance_records(next_maintenance_date);
CREATE INDEX idx_maintenance_records_status ON asset.maintenance_records(status);

-- ---------------------------------------------------------------------------
-- Subscriptions / intangible asset detail
-- ---------------------------------------------------------------------------

CREATE TABLE asset.subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id BIGINT NULL,
    vendor_id BIGINT NULL,
    software_name VARCHAR(180) NOT NULL,
    plan_name VARCHAR(120) NULL,
    license_key VARCHAR(500) NULL,
    owner_employee_id BIGINT NULL,
    total_seats INTEGER NOT NULL DEFAULT 0,
    used_seats INTEGER NOT NULL DEFAULT 0,
    billing_cycle VARCHAR(20) NULL,
    cost NUMERIC(18,2) NULL,
    start_date DATE NULL,
    renewal_date DATE NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    notes VARCHAR(500) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    updated_at TIMESTAMP NOT NULL DEFAULT now(),

    CONSTRAINT fk_subscriptions_asset
        FOREIGN KEY (asset_id) REFERENCES asset.assets(id)
        ON DELETE SET NULL,
    CONSTRAINT fk_subscriptions_vendor
        FOREIGN KEY (vendor_id) REFERENCES asset.vendors(id)
        ON DELETE SET NULL,
    CONSTRAINT ck_subscriptions_seats
        CHECK (total_seats >= 0 AND used_seats >= 0 AND used_seats <= total_seats),
    CONSTRAINT ck_subscriptions_cost_non_negative
        CHECK (cost IS NULL OR cost >= 0)
);

CREATE INDEX idx_subscriptions_asset_id ON asset.subscriptions(asset_id);
CREATE INDEX idx_subscriptions_vendor_id ON asset.subscriptions(vendor_id);
CREATE INDEX idx_subscriptions_software_name ON asset.subscriptions(software_name);
CREATE INDEX idx_subscriptions_renewal_date ON asset.subscriptions(renewal_date);
CREATE INDEX idx_subscriptions_status ON asset.subscriptions(status);

-- ---------------------------------------------------------------------------
-- Purchase requests kept for compatibility with the current service.
-- This is not part of the core asset schema improvement.
-- ---------------------------------------------------------------------------

CREATE TABLE asset.purchase_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(180) NOT NULL,
    request_type VARCHAR(40) NOT NULL,
    requester_employee_id BIGINT NULL,
    department_id BIGINT NULL,
    site_id BIGINT NULL,
    project_id BIGINT NULL,
    estimated_cost NUMERIC(18,2) NULL,
    needed_date DATE NULL,
    reason TEXT NULL,
    notes VARCHAR(500) NULL,
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    updated_at TIMESTAMP NOT NULL DEFAULT now(),

    CONSTRAINT ck_purchase_requests_estimated_cost_non_negative
        CHECK (estimated_cost IS NULL OR estimated_cost >= 0)
);

CREATE INDEX idx_purchase_requests_requester_employee_id ON asset.purchase_requests(requester_employee_id);
CREATE INDEX idx_purchase_requests_department_id ON asset.purchase_requests(department_id);
CREATE INDEX idx_purchase_requests_site_id ON asset.purchase_requests(site_id);
CREATE INDEX idx_purchase_requests_project_id ON asset.purchase_requests(project_id);
CREATE INDEX idx_purchase_requests_status ON asset.purchase_requests(status);

-- ---------------------------------------------------------------------------
-- Contracts kept for compatibility with the current service.
-- ---------------------------------------------------------------------------

CREATE TABLE asset.contracts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_number VARCHAR(80) NOT NULL,
    title VARCHAR(200) NOT NULL,
    vendor_id BIGINT NULL,
    purchase_request_id BIGINT NULL,
    asset_id BIGINT NULL,
    contract_value NUMERIC(18,2) NULL,
    currency VARCHAR(10) NULL,
    sign_date DATE NULL,
    effective_from DATE NULL,
    effective_to DATE NULL,
    payment_terms TEXT NULL,
    attachment_object_key VARCHAR(500) NULL,
    attachment_url VARCHAR(500) NULL,
    document_id BIGINT NULL,
    status VARCHAR(30) NOT NULL,
    notes VARCHAR(1000) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    updated_at TIMESTAMP NOT NULL DEFAULT now(),

    CONSTRAINT uk_contracts_contract_number UNIQUE (contract_number),
    CONSTRAINT fk_contracts_vendor
        FOREIGN KEY (vendor_id) REFERENCES asset.vendors(id)
        ON DELETE SET NULL,
    CONSTRAINT fk_contracts_purchase_request
        FOREIGN KEY (purchase_request_id) REFERENCES asset.purchase_requests(id)
        ON DELETE SET NULL,
    CONSTRAINT fk_contracts_asset
        FOREIGN KEY (asset_id) REFERENCES asset.assets(id)
        ON DELETE SET NULL,
    CONSTRAINT fk_contracts_document
        FOREIGN KEY (document_id) REFERENCES asset.asset_documents(id)
        ON DELETE SET NULL,
    CONSTRAINT ck_contracts_contract_value_non_negative
        CHECK (contract_value IS NULL OR contract_value >= 0)
);

CREATE INDEX idx_contracts_contract_number ON asset.contracts(contract_number);
CREATE INDEX idx_contracts_vendor_id ON asset.contracts(vendor_id);
CREATE INDEX idx_contracts_purchase_request_id ON asset.contracts(purchase_request_id);
CREATE INDEX idx_contracts_asset_id ON asset.contracts(asset_id);
CREATE INDEX idx_contracts_status ON asset.contracts(status);

-- ---------------------------------------------------------------------------
-- Event polling cursor used by asset-service.
-- Mirrors db/migration/V2__consumer_event_offsets.sql.
-- ---------------------------------------------------------------------------

CREATE TABLE asset.consumer_event_offsets (
    consumer_name TEXT PRIMARY KEY,
    last_sequence_id BIGINT NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
