-- ============================================================================
-- QLVT asset schema refactor, production-safe expand migration.
--
-- This migration mirrors the improved schema from:
--   src/main/resources/db/init_qlvt_asset_schema.sql
--
-- It intentionally does NOT drop the asset schema. It supports:
--   * fresh databases bootstrapped by Flyway;
--   * existing databases that were previously shaped by Hibernate ddl-auto.
--
-- Compatibility note:
-- The current backend still writes the old asset payload shape. A temporary
-- trigger fills the new required classification columns until the backend is
-- moved to the new contract.
-- ============================================================================

CREATE SCHEMA IF NOT EXISTS asset;

-- ---------------------------------------------------------------------------
-- Master data: asset categories
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS asset.asset_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(60) NOT NULL,
    name VARCHAR(180) NOT NULL,
    parent_id BIGINT NULL,
    asset_class VARCHAR(40) NOT NULL,
    description VARCHAR(500) NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    updated_at TIMESTAMP NOT NULL DEFAULT now(),
    CONSTRAINT uk_asset_categories_code UNIQUE (code)
);

ALTER TABLE asset.asset_categories ADD COLUMN IF NOT EXISTS code VARCHAR(60);
ALTER TABLE asset.asset_categories ADD COLUMN IF NOT EXISTS name VARCHAR(180);
ALTER TABLE asset.asset_categories ADD COLUMN IF NOT EXISTS parent_id BIGINT;
ALTER TABLE asset.asset_categories ADD COLUMN IF NOT EXISTS asset_class VARCHAR(40);
ALTER TABLE asset.asset_categories ADD COLUMN IF NOT EXISTS description VARCHAR(500);
ALTER TABLE asset.asset_categories ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE asset.asset_categories ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT now();
ALTER TABLE asset.asset_categories ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT now();

INSERT INTO asset.asset_categories (code, name, asset_class, description)
VALUES
    ('FIXED_ASSET', 'Tai san co dinh', 'FIXED_ASSET', 'Nhom tai san co dinh'),
    ('TOOL_EQUIPMENT', 'Cong cu dung cu', 'TOOL_EQUIPMENT', 'Nhom cong cu dung cu')
ON CONFLICT (code) DO NOTHING;

INSERT INTO asset.asset_categories (code, name, parent_id, asset_class, description)
VALUES
    (
        'TANGIBLE',
        'Tai san huu hinh',
        (SELECT id FROM asset.asset_categories WHERE code = 'FIXED_ASSET'),
        'FIXED_ASSET',
        'May moc, xe, thiet bi, nha xuong, vat kien truc'
    ),
    (
        'INTANGIBLE',
        'Tai san vo hinh',
        (SELECT id FROM asset.asset_categories WHERE code = 'FIXED_ASSET'),
        'FIXED_ASSET',
        'Ban quyen phan mem, license, quyen su dung, goi dich vu dai han'
    ),
    (
        'TOOL_SINGLE_USE',
        'Cong cu dung mot lan',
        (SELECT id FROM asset.asset_categories WHERE code = 'TOOL_EQUIPMENT'),
        'TOOL_EQUIPMENT',
        'Cong cu dung cu dung mot lan'
    ),
    (
        'TOOL_MULTI_USE',
        'Cong cu dung nhieu lan',
        (SELECT id FROM asset.asset_categories WHERE code = 'TOOL_EQUIPMENT'),
        'TOOL_EQUIPMENT',
        'Cong cu dung cu dung nhieu lan'
    )
ON CONFLICT (code) DO NOTHING;

CREATE INDEX IF NOT EXISTS idx_asset_categories_parent_id ON asset.asset_categories(parent_id);
CREATE INDEX IF NOT EXISTS idx_asset_categories_asset_class ON asset.asset_categories(asset_class);
CREATE INDEX IF NOT EXISTS idx_asset_categories_is_active ON asset.asset_categories(is_active);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE connamespace = 'asset'::regnamespace
          AND conname = 'fk_asset_categories_parent'
    ) THEN
        ALTER TABLE asset.asset_categories
            ADD CONSTRAINT fk_asset_categories_parent
            FOREIGN KEY (parent_id) REFERENCES asset.asset_categories(id)
            ON DELETE RESTRICT NOT VALID;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE connamespace = 'asset'::regnamespace
          AND conname = 'ck_asset_categories_asset_class'
    ) THEN
        ALTER TABLE asset.asset_categories
            ADD CONSTRAINT ck_asset_categories_asset_class
            CHECK (asset_class IN ('FIXED_ASSET', 'TOOL_EQUIPMENT')) NOT VALID;
    END IF;
END $$;

-- ---------------------------------------------------------------------------
-- Vendors
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS asset.vendors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(180) NOT NULL,
    tax_code VARCHAR(80) NULL,
    contact_name VARCHAR(120) NULL,
    phone VARCHAR(40) NULL,
    email VARCHAR(120) NULL,
    address VARCHAR(500) NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    updated_at TIMESTAMP NOT NULL DEFAULT now()
);

ALTER TABLE asset.vendors ADD COLUMN IF NOT EXISTS name VARCHAR(180);
ALTER TABLE asset.vendors ADD COLUMN IF NOT EXISTS tax_code VARCHAR(80);
ALTER TABLE asset.vendors ADD COLUMN IF NOT EXISTS contact_name VARCHAR(120);
ALTER TABLE asset.vendors ADD COLUMN IF NOT EXISTS phone VARCHAR(40);
ALTER TABLE asset.vendors ADD COLUMN IF NOT EXISTS email VARCHAR(120);
ALTER TABLE asset.vendors ADD COLUMN IF NOT EXISTS address VARCHAR(500);
ALTER TABLE asset.vendors ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE';
ALTER TABLE asset.vendors ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT now();
ALTER TABLE asset.vendors ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT now();

CREATE UNIQUE INDEX IF NOT EXISTS uk_vendors_tax_code
    ON asset.vendors(tax_code)
    WHERE tax_code IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_vendors_name ON asset.vendors(name);
CREATE INDEX IF NOT EXISTS idx_vendors_status ON asset.vendors(status);

-- ---------------------------------------------------------------------------
-- Catalog items
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS asset.asset_catalog_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_code VARCHAR(80) NOT NULL,
    name VARCHAR(255) NOT NULL,
    category_id BIGINT NULL,
    catalog_type VARCHAR(40) NOT NULL,
    inventory_group VARCHAR(120) NULL,
    unit VARCHAR(40) NULL,
    cost_value NUMERIC(18,2) NULL,
    standard_value NUMERIC(18,2) NULL,
    fixed_value NUMERIC(18,2) NULL,
    internal_value NUMERIC(18,2) NULL,
    technical_spec VARCHAR(1000) NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    updated_at TIMESTAMP NOT NULL DEFAULT now(),
    CONSTRAINT uk_asset_catalog_items_item_code UNIQUE (item_code)
);

ALTER TABLE asset.asset_catalog_items ADD COLUMN IF NOT EXISTS item_code VARCHAR(80);
ALTER TABLE asset.asset_catalog_items ADD COLUMN IF NOT EXISTS name VARCHAR(255);
ALTER TABLE asset.asset_catalog_items ADD COLUMN IF NOT EXISTS category_id BIGINT;
ALTER TABLE asset.asset_catalog_items ADD COLUMN IF NOT EXISTS catalog_type VARCHAR(40);
ALTER TABLE asset.asset_catalog_items ADD COLUMN IF NOT EXISTS inventory_group VARCHAR(120);
ALTER TABLE asset.asset_catalog_items ADD COLUMN IF NOT EXISTS unit VARCHAR(40);
ALTER TABLE asset.asset_catalog_items ADD COLUMN IF NOT EXISTS cost_value NUMERIC(18,2);
ALTER TABLE asset.asset_catalog_items ADD COLUMN IF NOT EXISTS standard_value NUMERIC(18,2);
ALTER TABLE asset.asset_catalog_items ADD COLUMN IF NOT EXISTS fixed_value NUMERIC(18,2);
ALTER TABLE asset.asset_catalog_items ADD COLUMN IF NOT EXISTS internal_value NUMERIC(18,2);
ALTER TABLE asset.asset_catalog_items ADD COLUMN IF NOT EXISTS technical_spec VARCHAR(1000);
ALTER TABLE asset.asset_catalog_items ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE asset.asset_catalog_items ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT now();
ALTER TABLE asset.asset_catalog_items ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT now();

CREATE INDEX IF NOT EXISTS idx_asset_catalog_items_category_id ON asset.asset_catalog_items(category_id);
CREATE INDEX IF NOT EXISTS idx_asset_catalog_items_catalog_type ON asset.asset_catalog_items(catalog_type);
CREATE INDEX IF NOT EXISTS idx_asset_catalog_items_name ON asset.asset_catalog_items(name);
CREATE INDEX IF NOT EXISTS idx_asset_catalog_items_is_active ON asset.asset_catalog_items(is_active);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE connamespace = 'asset'::regnamespace
          AND conname = 'fk_asset_catalog_items_category'
    ) THEN
        ALTER TABLE asset.asset_catalog_items
            ADD CONSTRAINT fk_asset_catalog_items_category
            FOREIGN KEY (category_id) REFERENCES asset.asset_categories(id)
            ON DELETE SET NULL NOT VALID;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE connamespace = 'asset'::regnamespace
          AND conname = 'ck_asset_catalog_items_catalog_type'
    ) THEN
        ALTER TABLE asset.asset_catalog_items
            ADD CONSTRAINT ck_asset_catalog_items_catalog_type
            CHECK (catalog_type IN ('ASSET', 'TOOL', 'MATERIAL', 'PRODUCT_REFERENCE')) NOT VALID;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE connamespace = 'asset'::regnamespace
          AND conname = 'ck_asset_catalog_items_values_non_negative'
    ) THEN
        ALTER TABLE asset.asset_catalog_items
            ADD CONSTRAINT ck_asset_catalog_items_values_non_negative
            CHECK (
                (cost_value IS NULL OR cost_value >= 0)
                AND (standard_value IS NULL OR standard_value >= 0)
                AND (fixed_value IS NULL OR fixed_value >= 0)
                AND (internal_value IS NULL OR internal_value >= 0)
            ) NOT VALID;
    END IF;
END $$;

-- ---------------------------------------------------------------------------
-- Assets
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS asset.assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_code VARCHAR(80) NOT NULL,
    name VARCHAR(255) NOT NULL,
    catalog_item_id BIGINT NULL,
    category_id BIGINT NULL,
    category VARCHAR(80) NULL,
    parent_asset_id BIGINT NULL,
    asset_class VARCHAR(40) NULL,
    fixed_asset_type VARCHAR(40) NULL,
    tool_usage_type VARCHAR(40) NULL,
    serial_number VARCHAR(120) NULL,
    source VARCHAR(120) NULL,
    vendor_id BIGINT NULL,
    assigned_employee_id BIGINT NULL,
    department_id BIGINT NULL,
    site_id BIGINT NULL,
    project_id BIGINT NULL,
    purchase_date DATE NULL,
    use_date DATE NULL,
    depreciation_start_date DATE NULL,
    warranty_until DATE NULL,
    original_cost NUMERIC(18,2) NULL,
    purchase_cost NUMERIC(18,2) NULL,
    accumulated_depreciation NUMERIC(18,2) NOT NULL DEFAULT 0,
    book_value NUMERIC(18,2) NULL,
    residual_value NUMERIC(18,2) NULL,
    depreciation_method VARCHAR(40) NULL DEFAULT 'STRAIGHT_LINE',
    useful_life_months INTEGER NULL,
    useful_life_years INTEGER NULL,
    depreciation_rate NUMERIC(8,4) NULL,
    manufacture_year INTEGER NULL,
    installation_year INTEGER NULL,
    country_code VARCHAR(10) NULL,
    capacity NUMERIC(18,4) NULL,
    capacity_unit VARCHAR(40) NULL,
    real_capacity NUMERIC(18,4) NULL,
    technical_description VARCHAR(2000) NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'IN_STOCK',
    disposal_date DATE NULL,
    disposal_price NUMERIC(18,2) NULL,
    disposal_reason VARCHAR(500) NULL,
    notes VARCHAR(1000) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    updated_at TIMESTAMP NOT NULL DEFAULT now()
);

ALTER TABLE asset.assets ADD COLUMN IF NOT EXISTS asset_code VARCHAR(80);
ALTER TABLE asset.assets ADD COLUMN IF NOT EXISTS name VARCHAR(255);
ALTER TABLE asset.assets ADD COLUMN IF NOT EXISTS catalog_item_id BIGINT;
ALTER TABLE asset.assets ADD COLUMN IF NOT EXISTS category_id BIGINT;
ALTER TABLE asset.assets ADD COLUMN IF NOT EXISTS category VARCHAR(80);
ALTER TABLE asset.assets ADD COLUMN IF NOT EXISTS parent_asset_id BIGINT;
ALTER TABLE asset.assets ADD COLUMN IF NOT EXISTS asset_class VARCHAR(40);
ALTER TABLE asset.assets ADD COLUMN IF NOT EXISTS fixed_asset_type VARCHAR(40);
ALTER TABLE asset.assets ADD COLUMN IF NOT EXISTS tool_usage_type VARCHAR(40);
ALTER TABLE asset.assets ADD COLUMN IF NOT EXISTS serial_number VARCHAR(120);
ALTER TABLE asset.assets ADD COLUMN IF NOT EXISTS source VARCHAR(120);
ALTER TABLE asset.assets ADD COLUMN IF NOT EXISTS vendor_id BIGINT;
ALTER TABLE asset.assets ADD COLUMN IF NOT EXISTS assigned_employee_id BIGINT;
ALTER TABLE asset.assets ADD COLUMN IF NOT EXISTS department_id BIGINT;
ALTER TABLE asset.assets ADD COLUMN IF NOT EXISTS site_id BIGINT;
ALTER TABLE asset.assets ADD COLUMN IF NOT EXISTS project_id BIGINT;
ALTER TABLE asset.assets ADD COLUMN IF NOT EXISTS purchase_date DATE;
ALTER TABLE asset.assets ADD COLUMN IF NOT EXISTS use_date DATE;
ALTER TABLE asset.assets ADD COLUMN IF NOT EXISTS depreciation_start_date DATE;
ALTER TABLE asset.assets ADD COLUMN IF NOT EXISTS warranty_until DATE;
ALTER TABLE asset.assets ADD COLUMN IF NOT EXISTS original_cost NUMERIC(18,2);
ALTER TABLE asset.assets ADD COLUMN IF NOT EXISTS purchase_cost NUMERIC(18,2);
ALTER TABLE asset.assets ADD COLUMN IF NOT EXISTS accumulated_depreciation NUMERIC(18,2) NOT NULL DEFAULT 0;
ALTER TABLE asset.assets ADD COLUMN IF NOT EXISTS book_value NUMERIC(18,2);
ALTER TABLE asset.assets ADD COLUMN IF NOT EXISTS residual_value NUMERIC(18,2);
ALTER TABLE asset.assets ADD COLUMN IF NOT EXISTS depreciation_method VARCHAR(40) DEFAULT 'STRAIGHT_LINE';
ALTER TABLE asset.assets ADD COLUMN IF NOT EXISTS useful_life_months INTEGER;
ALTER TABLE asset.assets ADD COLUMN IF NOT EXISTS useful_life_years INTEGER;
ALTER TABLE asset.assets ADD COLUMN IF NOT EXISTS depreciation_rate NUMERIC(8,4);
ALTER TABLE asset.assets ADD COLUMN IF NOT EXISTS manufacture_year INTEGER;
ALTER TABLE asset.assets ADD COLUMN IF NOT EXISTS installation_year INTEGER;
ALTER TABLE asset.assets ADD COLUMN IF NOT EXISTS country_code VARCHAR(10);
ALTER TABLE asset.assets ADD COLUMN IF NOT EXISTS capacity NUMERIC(18,4);
ALTER TABLE asset.assets ADD COLUMN IF NOT EXISTS capacity_unit VARCHAR(40);
ALTER TABLE asset.assets ADD COLUMN IF NOT EXISTS real_capacity NUMERIC(18,4);
ALTER TABLE asset.assets ADD COLUMN IF NOT EXISTS technical_description VARCHAR(2000);
ALTER TABLE asset.assets ADD COLUMN IF NOT EXISTS status VARCHAR(30) NOT NULL DEFAULT 'IN_STOCK';
ALTER TABLE asset.assets ADD COLUMN IF NOT EXISTS disposal_date DATE;
ALTER TABLE asset.assets ADD COLUMN IF NOT EXISTS disposal_price NUMERIC(18,2);
ALTER TABLE asset.assets ADD COLUMN IF NOT EXISTS disposal_reason VARCHAR(500);
ALTER TABLE asset.assets ADD COLUMN IF NOT EXISTS notes VARCHAR(1000);
ALTER TABLE asset.assets ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT now();
ALTER TABLE asset.assets ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT now();

CREATE OR REPLACE FUNCTION asset.fill_asset_classification_defaults()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    default_category_code TEXT;
    default_category_id BIGINT;
    existing_asset_class TEXT;
BEGIN
    SELECT c.asset_class
    INTO existing_asset_class
    FROM asset.asset_categories c
    WHERE c.id = NEW.category_id;

    IF NEW.asset_class IS NULL THEN
        IF existing_asset_class IS NOT NULL THEN
            NEW.asset_class := existing_asset_class;
        ELSIF NEW.category IS NOT NULL
            AND (
                lower(NEW.category) LIKE '%tool%'
                OR lower(NEW.category) LIKE '%cong cu%'
                OR lower(NEW.category) LIKE '%dung cu%'
            ) THEN
            NEW.asset_class := 'TOOL_EQUIPMENT';
        ELSE
            NEW.asset_class := 'FIXED_ASSET';
        END IF;
    END IF;

    IF NEW.asset_class = 'TOOL_EQUIPMENT' THEN
        IF NEW.tool_usage_type IS NULL THEN
            NEW.tool_usage_type := 'MULTI_USE';
        END IF;
        default_category_code := 'TOOL_MULTI_USE';
    ELSE
        IF NEW.fixed_asset_type IS NULL THEN
            NEW.fixed_asset_type := 'TANGIBLE';
        END IF;
        default_category_code := 'TANGIBLE';
    END IF;

    IF NEW.category_id IS NULL THEN
        SELECT id
        INTO default_category_id
        FROM asset.asset_categories
        WHERE code = default_category_code;

        NEW.category_id := default_category_id;
    END IF;

    IF NEW.original_cost IS NULL AND NEW.purchase_cost IS NOT NULL THEN
        NEW.original_cost := NEW.purchase_cost;
    END IF;

    IF NEW.accumulated_depreciation IS NULL THEN
        NEW.accumulated_depreciation := 0;
    END IF;

    IF NEW.book_value IS NULL THEN
        NEW.book_value := COALESCE(NEW.residual_value, NEW.original_cost, NEW.purchase_cost);
    END IF;

    IF NEW.useful_life_months IS NULL AND NEW.useful_life_years IS NOT NULL THEN
        NEW.useful_life_months := NEW.useful_life_years * 12;
    END IF;

    RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS trg_assets_fill_classification_defaults ON asset.assets;
CREATE TRIGGER trg_assets_fill_classification_defaults
BEFORE INSERT OR UPDATE ON asset.assets
FOR EACH ROW
EXECUTE FUNCTION asset.fill_asset_classification_defaults();

UPDATE asset.assets
SET updated_at = COALESCE(updated_at, now())
WHERE updated_at IS NULL;

UPDATE asset.assets
SET asset_class = COALESCE(
        asset_class,
        CASE
            WHEN category IS NOT NULL
             AND (
                lower(category) LIKE '%tool%'
                OR lower(category) LIKE '%cong cu%'
                OR lower(category) LIKE '%dung cu%'
             )
            THEN 'TOOL_EQUIPMENT'
            ELSE 'FIXED_ASSET'
        END
    ),
    fixed_asset_type = CASE
        WHEN COALESCE(asset_class, 'FIXED_ASSET') = 'FIXED_ASSET'
        THEN COALESCE(fixed_asset_type, 'TANGIBLE')
        ELSE fixed_asset_type
    END,
    tool_usage_type = CASE
        WHEN COALESCE(asset_class, 'FIXED_ASSET') = 'TOOL_EQUIPMENT'
        THEN COALESCE(tool_usage_type, 'MULTI_USE')
        ELSE tool_usage_type
    END,
    original_cost = COALESCE(original_cost, purchase_cost),
    accumulated_depreciation = COALESCE(accumulated_depreciation, 0),
    book_value = COALESCE(book_value, residual_value, original_cost, purchase_cost),
    useful_life_months = COALESCE(useful_life_months, useful_life_years * 12),
    depreciation_method = COALESCE(depreciation_method, 'STRAIGHT_LINE')
WHERE asset_class IS NULL
   OR category_id IS NULL
   OR original_cost IS NULL
   OR accumulated_depreciation IS NULL
   OR book_value IS NULL
   OR (useful_life_months IS NULL AND useful_life_years IS NOT NULL)
   OR depreciation_method IS NULL;

UPDATE asset.assets a
SET category_id = c.id
FROM asset.asset_categories c
WHERE a.category_id IS NULL
  AND c.code = CASE
      WHEN a.asset_class = 'TOOL_EQUIPMENT' THEN 'TOOL_MULTI_USE'
      ELSE 'TANGIBLE'
  END;

ALTER TABLE asset.assets ALTER COLUMN category_id SET NOT NULL;
ALTER TABLE asset.assets ALTER COLUMN asset_class SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uk_assets_asset_code ON asset.assets(asset_code);
CREATE INDEX IF NOT EXISTS idx_assets_asset_code ON asset.assets(asset_code);
CREATE INDEX IF NOT EXISTS idx_assets_name ON asset.assets(name);
CREATE INDEX IF NOT EXISTS idx_assets_catalog_item_id ON asset.assets(catalog_item_id);
CREATE INDEX IF NOT EXISTS idx_assets_category_id ON asset.assets(category_id);
CREATE INDEX IF NOT EXISTS idx_assets_category ON asset.assets(category);
CREATE INDEX IF NOT EXISTS idx_assets_parent_asset_id ON asset.assets(parent_asset_id);
CREATE INDEX IF NOT EXISTS idx_assets_asset_class ON asset.assets(asset_class);
CREATE INDEX IF NOT EXISTS idx_assets_status ON asset.assets(status);
CREATE INDEX IF NOT EXISTS idx_assets_assigned_employee_id ON asset.assets(assigned_employee_id);
CREATE INDEX IF NOT EXISTS idx_assets_department_id ON asset.assets(department_id);
CREATE INDEX IF NOT EXISTS idx_assets_site_id ON asset.assets(site_id);
CREATE INDEX IF NOT EXISTS idx_assets_project_id ON asset.assets(project_id);
CREATE INDEX IF NOT EXISTS idx_assets_vendor_id ON asset.assets(vendor_id);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE connamespace = 'asset'::regnamespace
          AND conname = 'fk_assets_catalog_item'
    ) THEN
        ALTER TABLE asset.assets
            ADD CONSTRAINT fk_assets_catalog_item
            FOREIGN KEY (catalog_item_id) REFERENCES asset.asset_catalog_items(id)
            ON DELETE SET NULL NOT VALID;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE connamespace = 'asset'::regnamespace
          AND conname = 'fk_assets_category'
    ) THEN
        ALTER TABLE asset.assets
            ADD CONSTRAINT fk_assets_category
            FOREIGN KEY (category_id) REFERENCES asset.asset_categories(id)
            ON DELETE RESTRICT NOT VALID;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE connamespace = 'asset'::regnamespace
          AND conname = 'fk_assets_parent_asset'
    ) THEN
        ALTER TABLE asset.assets
            ADD CONSTRAINT fk_assets_parent_asset
            FOREIGN KEY (parent_asset_id) REFERENCES asset.assets(id)
            ON DELETE SET NULL NOT VALID;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE connamespace = 'asset'::regnamespace
          AND conname = 'fk_assets_vendor'
    ) THEN
        ALTER TABLE asset.assets
            ADD CONSTRAINT fk_assets_vendor
            FOREIGN KEY (vendor_id) REFERENCES asset.vendors(id)
            ON DELETE SET NULL NOT VALID;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE connamespace = 'asset'::regnamespace
          AND conname = 'ck_assets_asset_class'
    ) THEN
        ALTER TABLE asset.assets
            ADD CONSTRAINT ck_assets_asset_class
            CHECK (asset_class IN ('FIXED_ASSET', 'TOOL_EQUIPMENT')) NOT VALID;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE connamespace = 'asset'::regnamespace
          AND conname = 'ck_assets_fixed_asset_type'
    ) THEN
        ALTER TABLE asset.assets
            ADD CONSTRAINT ck_assets_fixed_asset_type
            CHECK (fixed_asset_type IS NULL OR fixed_asset_type IN ('TANGIBLE', 'INTANGIBLE')) NOT VALID;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE connamespace = 'asset'::regnamespace
          AND conname = 'ck_assets_tool_usage_type'
    ) THEN
        ALTER TABLE asset.assets
            ADD CONSTRAINT ck_assets_tool_usage_type
            CHECK (tool_usage_type IS NULL OR tool_usage_type IN ('SINGLE_USE', 'MULTI_USE')) NOT VALID;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE connamespace = 'asset'::regnamespace
          AND conname = 'ck_assets_fixed_asset_type_required'
    ) THEN
        ALTER TABLE asset.assets
            ADD CONSTRAINT ck_assets_fixed_asset_type_required
            CHECK (asset_class <> 'FIXED_ASSET' OR fixed_asset_type IS NOT NULL) NOT VALID;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE connamespace = 'asset'::regnamespace
          AND conname = 'ck_assets_tool_usage_type_required'
    ) THEN
        ALTER TABLE asset.assets
            ADD CONSTRAINT ck_assets_tool_usage_type_required
            CHECK (asset_class <> 'TOOL_EQUIPMENT' OR tool_usage_type IS NOT NULL) NOT VALID;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE connamespace = 'asset'::regnamespace
          AND conname = 'ck_assets_status'
    ) THEN
        ALTER TABLE asset.assets
            ADD CONSTRAINT ck_assets_status
            CHECK (status IN ('IN_STOCK', 'ASSIGNED', 'MAINTENANCE', 'LOST', 'DISPOSED', 'PENDING')) NOT VALID;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE connamespace = 'asset'::regnamespace
          AND conname = 'ck_assets_depreciation_method'
    ) THEN
        ALTER TABLE asset.assets
            ADD CONSTRAINT ck_assets_depreciation_method
            CHECK (
                depreciation_method IS NULL
                OR depreciation_method IN ('STRAIGHT_LINE', 'DECLINING_BALANCE', 'NONE')
            ) NOT VALID;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE connamespace = 'asset'::regnamespace
          AND conname = 'ck_assets_money_non_negative'
    ) THEN
        ALTER TABLE asset.assets
            ADD CONSTRAINT ck_assets_money_non_negative
            CHECK (
                (original_cost IS NULL OR original_cost >= 0)
                AND (purchase_cost IS NULL OR purchase_cost >= 0)
                AND (accumulated_depreciation >= 0)
                AND (book_value IS NULL OR book_value >= 0)
                AND (residual_value IS NULL OR residual_value >= 0)
                AND (disposal_price IS NULL OR disposal_price >= 0)
            ) NOT VALID;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE connamespace = 'asset'::regnamespace
          AND conname = 'ck_assets_life_non_negative'
    ) THEN
        ALTER TABLE asset.assets
            ADD CONSTRAINT ck_assets_life_non_negative
            CHECK (
                (useful_life_months IS NULL OR useful_life_months >= 0)
                AND (useful_life_years IS NULL OR useful_life_years >= 0)
                AND (depreciation_rate IS NULL OR depreciation_rate >= 0)
            ) NOT VALID;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE connamespace = 'asset'::regnamespace
          AND conname = 'ck_assets_capacity_non_negative'
    ) THEN
        ALTER TABLE asset.assets
            ADD CONSTRAINT ck_assets_capacity_non_negative
            CHECK (
                (capacity IS NULL OR capacity >= 0)
                AND (real_capacity IS NULL OR real_capacity >= 0)
            ) NOT VALID;
    END IF;
END $$;

-- ---------------------------------------------------------------------------
-- Value snapshots
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS asset.asset_value_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id BIGINT NOT NULL,
    snapshot_date DATE NOT NULL,
    original_cost NUMERIC(18,2) NOT NULL,
    period_depreciation NUMERIC(18,2) NOT NULL DEFAULT 0,
    accumulated_depreciation NUMERIC(18,2) NOT NULL DEFAULT 0,
    book_value NUMERIC(18,2) NOT NULL,
    source VARCHAR(80) NOT NULL DEFAULT 'SYSTEM_CALCULATION',
    notes VARCHAR(500) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    CONSTRAINT uk_asset_value_snapshots_asset_date_source
        UNIQUE (asset_id, snapshot_date, source)
);

CREATE INDEX IF NOT EXISTS idx_asset_value_snapshots_asset_id ON asset.asset_value_snapshots(asset_id);
CREATE INDEX IF NOT EXISTS idx_asset_value_snapshots_snapshot_date ON asset.asset_value_snapshots(snapshot_date);
CREATE INDEX IF NOT EXISTS idx_asset_value_snapshots_source ON asset.asset_value_snapshots(source);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE connamespace = 'asset'::regnamespace
          AND conname = 'fk_asset_value_snapshots_asset'
    ) THEN
        ALTER TABLE asset.asset_value_snapshots
            ADD CONSTRAINT fk_asset_value_snapshots_asset
            FOREIGN KEY (asset_id) REFERENCES asset.assets(id)
            ON DELETE CASCADE NOT VALID;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE connamespace = 'asset'::regnamespace
          AND conname = 'ck_asset_value_snapshots_source'
    ) THEN
        ALTER TABLE asset.asset_value_snapshots
            ADD CONSTRAINT ck_asset_value_snapshots_source
            CHECK (source IN ('IMPORT', 'SYSTEM_CALCULATION', 'MANUAL_ADJUSTMENT')) NOT VALID;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE connamespace = 'asset'::regnamespace
          AND conname = 'ck_asset_value_snapshots_money_non_negative'
    ) THEN
        ALTER TABLE asset.asset_value_snapshots
            ADD CONSTRAINT ck_asset_value_snapshots_money_non_negative
            CHECK (
                original_cost >= 0
                AND period_depreciation >= 0
                AND accumulated_depreciation >= 0
                AND book_value >= 0
            ) NOT VALID;
    END IF;
END $$;

-- ---------------------------------------------------------------------------
-- Asset documents / QR codes
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS asset.asset_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id BIGINT NOT NULL,
    document_type VARCHAR(50) NOT NULL DEFAULT 'OTHER',
    file_name VARCHAR(255) NOT NULL,
    object_key VARCHAR(500) NOT NULL,
    content_type VARCHAR(120) NULL,
    size_bytes BIGINT NULL,
    uploaded_by VARCHAR(200) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    CONSTRAINT uk_asset_documents_object_key UNIQUE (object_key)
);

CREATE INDEX IF NOT EXISTS idx_asset_documents_asset_id ON asset.asset_documents(asset_id);
CREATE INDEX IF NOT EXISTS idx_asset_documents_document_type ON asset.asset_documents(document_type);
CREATE INDEX IF NOT EXISTS idx_asset_documents_created_at ON asset.asset_documents(created_at);

CREATE TABLE IF NOT EXISTS asset.asset_qr_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id BIGINT NOT NULL,
    qr_payload VARCHAR(1000) NOT NULL,
    qr_token VARCHAR(120) NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    printed_at TIMESTAMP NULL,
    printed_by VARCHAR(200) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    CONSTRAINT uk_asset_qr_codes_qr_token UNIQUE (qr_token)
);

CREATE INDEX IF NOT EXISTS idx_asset_qr_codes_asset_id ON asset.asset_qr_codes(asset_id);
CREATE INDEX IF NOT EXISTS idx_asset_qr_codes_status ON asset.asset_qr_codes(status);
CREATE INDEX IF NOT EXISTS idx_asset_qr_codes_qr_token ON asset.asset_qr_codes(qr_token);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE connamespace = 'asset'::regnamespace
          AND conname = 'fk_asset_documents_asset'
    ) THEN
        ALTER TABLE asset.asset_documents
            ADD CONSTRAINT fk_asset_documents_asset
            FOREIGN KEY (asset_id) REFERENCES asset.assets(id)
            ON DELETE CASCADE NOT VALID;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE connamespace = 'asset'::regnamespace
          AND conname = 'ck_asset_documents_document_type'
    ) THEN
        ALTER TABLE asset.asset_documents
            ADD CONSTRAINT ck_asset_documents_document_type
            CHECK (document_type IN ('IMAGE', 'HANDOVER', 'INVOICE', 'WARRANTY', 'MAINTENANCE', 'DISPOSAL', 'OTHER')) NOT VALID;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE connamespace = 'asset'::regnamespace
          AND conname = 'ck_asset_documents_size_non_negative'
    ) THEN
        ALTER TABLE asset.asset_documents
            ADD CONSTRAINT ck_asset_documents_size_non_negative
            CHECK (size_bytes IS NULL OR size_bytes >= 0) NOT VALID;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE connamespace = 'asset'::regnamespace
          AND conname = 'fk_asset_qr_codes_asset'
    ) THEN
        ALTER TABLE asset.asset_qr_codes
            ADD CONSTRAINT fk_asset_qr_codes_asset
            FOREIGN KEY (asset_id) REFERENCES asset.assets(id)
            ON DELETE CASCADE NOT VALID;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE connamespace = 'asset'::regnamespace
          AND conname = 'ck_asset_qr_codes_status'
    ) THEN
        ALTER TABLE asset.asset_qr_codes
            ADD CONSTRAINT ck_asset_qr_codes_status
            CHECK (status IN ('ACTIVE', 'REVOKED')) NOT VALID;
    END IF;
END $$;

-- ---------------------------------------------------------------------------
-- Existing service tables: expand in place
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS asset.asset_transfers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id BIGINT NOT NULL,
    transfer_type VARCHAR(30) NOT NULL,
    transfer_date DATE NOT NULL,
    from_employee_id BIGINT NULL,
    to_employee_id BIGINT NULL,
    from_department_id BIGINT NULL,
    to_department_id BIGINT NULL,
    from_site_id BIGINT NULL,
    to_site_id BIGINT NULL,
    from_project_id BIGINT NULL,
    to_project_id BIGINT NULL,
    condition_before VARCHAR(500) NULL,
    condition_after VARCHAR(500) NULL,
    reason VARCHAR(1000) NULL,
    handover_document_url VARCHAR(500) NULL,
    handover_document_id BIGINT NULL,
    performed_by VARCHAR(200) NULL,
    approved_by VARCHAR(200) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT now()
);

ALTER TABLE asset.asset_transfers ADD COLUMN IF NOT EXISTS from_project_id BIGINT;
ALTER TABLE asset.asset_transfers ADD COLUMN IF NOT EXISTS to_project_id BIGINT;
ALTER TABLE asset.asset_transfers ADD COLUMN IF NOT EXISTS condition_before VARCHAR(500);
ALTER TABLE asset.asset_transfers ADD COLUMN IF NOT EXISTS condition_after VARCHAR(500);
ALTER TABLE asset.asset_transfers ADD COLUMN IF NOT EXISTS handover_document_id BIGINT;
ALTER TABLE asset.asset_transfers ADD COLUMN IF NOT EXISTS approved_by VARCHAR(200);

CREATE INDEX IF NOT EXISTS idx_asset_transfers_asset_id ON asset.asset_transfers(asset_id);
CREATE INDEX IF NOT EXISTS idx_asset_transfers_transfer_date ON asset.asset_transfers(transfer_date);
CREATE INDEX IF NOT EXISTS idx_asset_transfers_from_employee_id ON asset.asset_transfers(from_employee_id);
CREATE INDEX IF NOT EXISTS idx_asset_transfers_to_employee_id ON asset.asset_transfers(to_employee_id);
CREATE INDEX IF NOT EXISTS idx_asset_transfers_from_department_id ON asset.asset_transfers(from_department_id);
CREATE INDEX IF NOT EXISTS idx_asset_transfers_to_department_id ON asset.asset_transfers(to_department_id);

CREATE TABLE IF NOT EXISTS asset.maintenance_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id BIGINT NOT NULL,
    vendor_id BIGINT NULL,
    maintenance_type VARCHAR(30) NOT NULL,
    maintenance_date DATE NOT NULL,
    next_maintenance_date DATE NULL,
    performed_by VARCHAR(200) NULL,
    description VARCHAR(1000) NULL,
    cost NUMERIC(18,2) NULL,
    downtime_hours NUMERIC(10,2) NULL,
    meter_reading NUMERIC(18,2) NULL,
    condition_after VARCHAR(500) NULL,
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    updated_at TIMESTAMP NOT NULL DEFAULT now()
);

ALTER TABLE asset.maintenance_records ADD COLUMN IF NOT EXISTS downtime_hours NUMERIC(10,2);
ALTER TABLE asset.maintenance_records ADD COLUMN IF NOT EXISTS meter_reading NUMERIC(18,2);
ALTER TABLE asset.maintenance_records ADD COLUMN IF NOT EXISTS condition_after VARCHAR(500);

CREATE INDEX IF NOT EXISTS idx_maintenance_records_asset_id ON asset.maintenance_records(asset_id);
CREATE INDEX IF NOT EXISTS idx_maintenance_records_vendor_id ON asset.maintenance_records(vendor_id);
CREATE INDEX IF NOT EXISTS idx_maintenance_records_maintenance_date ON asset.maintenance_records(maintenance_date);
CREATE INDEX IF NOT EXISTS idx_maintenance_records_next_maintenance_date ON asset.maintenance_records(next_maintenance_date);
CREATE INDEX IF NOT EXISTS idx_maintenance_records_status ON asset.maintenance_records(status);

CREATE TABLE IF NOT EXISTS asset.subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id BIGINT NULL,
    vendor_id BIGINT NULL,
    software_name VARCHAR(180) NOT NULL,
    plan_name VARCHAR(120) NULL,
    license_key VARCHAR(500) NULL,
    owner_employee_id BIGINT NULL,
    total_seats INTEGER NOT NULL DEFAULT 0,
    used_seats INTEGER NOT NULL DEFAULT 0,
    billing_cycle VARCHAR(20) NULL,
    cost NUMERIC(18,2) NULL,
    start_date DATE NULL,
    renewal_date DATE NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    notes VARCHAR(500) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    updated_at TIMESTAMP NOT NULL DEFAULT now()
);

ALTER TABLE asset.subscriptions ADD COLUMN IF NOT EXISTS asset_id BIGINT;
ALTER TABLE asset.subscriptions ADD COLUMN IF NOT EXISTS license_key VARCHAR(500);
ALTER TABLE asset.subscriptions ADD COLUMN IF NOT EXISTS owner_employee_id BIGINT;

CREATE INDEX IF NOT EXISTS idx_subscriptions_asset_id ON asset.subscriptions(asset_id);
CREATE INDEX IF NOT EXISTS idx_subscriptions_vendor_id ON asset.subscriptions(vendor_id);
CREATE INDEX IF NOT EXISTS idx_subscriptions_software_name ON asset.subscriptions(software_name);
CREATE INDEX IF NOT EXISTS idx_subscriptions_renewal_date ON asset.subscriptions(renewal_date);
CREATE INDEX IF NOT EXISTS idx_subscriptions_status ON asset.subscriptions(status);

CREATE TABLE IF NOT EXISTS asset.purchase_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(180) NOT NULL,
    request_type VARCHAR(40) NOT NULL,
    requester_employee_id BIGINT NULL,
    department_id BIGINT NULL,
    site_id BIGINT NULL,
    project_id BIGINT NULL,
    estimated_cost NUMERIC(18,2) NULL,
    needed_date DATE NULL,
    reason TEXT NULL,
    notes VARCHAR(500) NULL,
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    updated_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_purchase_requests_requester_employee_id ON asset.purchase_requests(requester_employee_id);
CREATE INDEX IF NOT EXISTS idx_purchase_requests_department_id ON asset.purchase_requests(department_id);
CREATE INDEX IF NOT EXISTS idx_purchase_requests_site_id ON asset.purchase_requests(site_id);
CREATE INDEX IF NOT EXISTS idx_purchase_requests_project_id ON asset.purchase_requests(project_id);
CREATE INDEX IF NOT EXISTS idx_purchase_requests_status ON asset.purchase_requests(status);

CREATE TABLE IF NOT EXISTS asset.contracts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_number VARCHAR(80) NOT NULL,
    title VARCHAR(200) NOT NULL,
    vendor_id BIGINT NULL,
    purchase_request_id BIGINT NULL,
    asset_id BIGINT NULL,
    contract_value NUMERIC(18,2) NULL,
    currency VARCHAR(10) NULL,
    sign_date DATE NULL,
    effective_from DATE NULL,
    effective_to DATE NULL,
    payment_terms TEXT NULL,
    attachment_object_key VARCHAR(500) NULL,
    attachment_url VARCHAR(500) NULL,
    document_id BIGINT NULL,
    status VARCHAR(30) NOT NULL,
    notes VARCHAR(1000) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    updated_at TIMESTAMP NOT NULL DEFAULT now()
);

ALTER TABLE asset.contracts ADD COLUMN IF NOT EXISTS asset_id BIGINT;
ALTER TABLE asset.contracts ADD COLUMN IF NOT EXISTS document_id BIGINT;

CREATE UNIQUE INDEX IF NOT EXISTS uk_contracts_contract_number ON asset.contracts(contract_number);
CREATE INDEX IF NOT EXISTS idx_contracts_contract_number ON asset.contracts(contract_number);
CREATE INDEX IF NOT EXISTS idx_contracts_vendor_id ON asset.contracts(vendor_id);
CREATE INDEX IF NOT EXISTS idx_contracts_purchase_request_id ON asset.contracts(purchase_request_id);
CREATE INDEX IF NOT EXISTS idx_contracts_asset_id ON asset.contracts(asset_id);
CREATE INDEX IF NOT EXISTS idx_contracts_status ON asset.contracts(status);

-- Shared FK/check constraints for expanded existing service tables.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE connamespace = 'asset'::regnamespace
          AND conname = 'fk_asset_transfers_asset'
    ) THEN
        ALTER TABLE asset.asset_transfers
            ADD CONSTRAINT fk_asset_transfers_asset
            FOREIGN KEY (asset_id) REFERENCES asset.assets(id)
            ON DELETE CASCADE NOT VALID;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE connamespace = 'asset'::regnamespace
          AND conname = 'fk_asset_transfers_handover_document'
    ) THEN
        ALTER TABLE asset.asset_transfers
            ADD CONSTRAINT fk_asset_transfers_handover_document
            FOREIGN KEY (handover_document_id) REFERENCES asset.asset_documents(id)
            ON DELETE SET NULL NOT VALID;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE connamespace = 'asset'::regnamespace
          AND conname = 'fk_maintenance_records_asset'
    ) THEN
        ALTER TABLE asset.maintenance_records
            ADD CONSTRAINT fk_maintenance_records_asset
            FOREIGN KEY (asset_id) REFERENCES asset.assets(id)
            ON DELETE CASCADE NOT VALID;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE connamespace = 'asset'::regnamespace
          AND conname = 'fk_maintenance_records_vendor'
    ) THEN
        ALTER TABLE asset.maintenance_records
            ADD CONSTRAINT fk_maintenance_records_vendor
            FOREIGN KEY (vendor_id) REFERENCES asset.vendors(id)
            ON DELETE SET NULL NOT VALID;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE connamespace = 'asset'::regnamespace
          AND conname = 'ck_maintenance_records_numbers_non_negative'
    ) THEN
        ALTER TABLE asset.maintenance_records
            ADD CONSTRAINT ck_maintenance_records_numbers_non_negative
            CHECK (
                (cost IS NULL OR cost >= 0)
                AND (downtime_hours IS NULL OR downtime_hours >= 0)
                AND (meter_reading IS NULL OR meter_reading >= 0)
            ) NOT VALID;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE connamespace = 'asset'::regnamespace
          AND conname = 'fk_subscriptions_asset'
    ) THEN
        ALTER TABLE asset.subscriptions
            ADD CONSTRAINT fk_subscriptions_asset
            FOREIGN KEY (asset_id) REFERENCES asset.assets(id)
            ON DELETE SET NULL NOT VALID;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE connamespace = 'asset'::regnamespace
          AND conname = 'fk_subscriptions_vendor'
    ) THEN
        ALTER TABLE asset.subscriptions
            ADD CONSTRAINT fk_subscriptions_vendor
            FOREIGN KEY (vendor_id) REFERENCES asset.vendors(id)
            ON DELETE SET NULL NOT VALID;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE connamespace = 'asset'::regnamespace
          AND conname = 'ck_subscriptions_seats'
    ) THEN
        ALTER TABLE asset.subscriptions
            ADD CONSTRAINT ck_subscriptions_seats
            CHECK (total_seats >= 0 AND used_seats >= 0 AND used_seats <= total_seats) NOT VALID;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE connamespace = 'asset'::regnamespace
          AND conname = 'ck_subscriptions_cost_non_negative'
    ) THEN
        ALTER TABLE asset.subscriptions
            ADD CONSTRAINT ck_subscriptions_cost_non_negative
            CHECK (cost IS NULL OR cost >= 0) NOT VALID;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE connamespace = 'asset'::regnamespace
          AND conname = 'ck_purchase_requests_estimated_cost_non_negative'
    ) THEN
        ALTER TABLE asset.purchase_requests
            ADD CONSTRAINT ck_purchase_requests_estimated_cost_non_negative
            CHECK (estimated_cost IS NULL OR estimated_cost >= 0) NOT VALID;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE connamespace = 'asset'::regnamespace
          AND conname = 'fk_contracts_vendor'
    ) THEN
        ALTER TABLE asset.contracts
            ADD CONSTRAINT fk_contracts_vendor
            FOREIGN KEY (vendor_id) REFERENCES asset.vendors(id)
            ON DELETE SET NULL NOT VALID;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE connamespace = 'asset'::regnamespace
          AND conname = 'fk_contracts_purchase_request'
    ) THEN
        ALTER TABLE asset.contracts
            ADD CONSTRAINT fk_contracts_purchase_request
            FOREIGN KEY (purchase_request_id) REFERENCES asset.purchase_requests(id)
            ON DELETE SET NULL NOT VALID;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE connamespace = 'asset'::regnamespace
          AND conname = 'fk_contracts_asset'
    ) THEN
        ALTER TABLE asset.contracts
            ADD CONSTRAINT fk_contracts_asset
            FOREIGN KEY (asset_id) REFERENCES asset.assets(id)
            ON DELETE SET NULL NOT VALID;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE connamespace = 'asset'::regnamespace
          AND conname = 'fk_contracts_document'
    ) THEN
        ALTER TABLE asset.contracts
            ADD CONSTRAINT fk_contracts_document
            FOREIGN KEY (document_id) REFERENCES asset.asset_documents(id)
            ON DELETE SET NULL NOT VALID;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE connamespace = 'asset'::regnamespace
          AND conname = 'ck_contracts_contract_value_non_negative'
    ) THEN
        ALTER TABLE asset.contracts
            ADD CONSTRAINT ck_contracts_contract_value_non_negative
            CHECK (contract_value IS NULL OR contract_value >= 0) NOT VALID;
    END IF;
END $$;
