-- GHI CHÚ: BẢNG asset_transfers lưu thông tin dòng tài sản trong một phiên bàn giao 
-- ============================================================================
-- V7 - Mở rộng nghiệp vụ bàn giao tài sản
--
--   1. Tao bang header cho "phieu ban giao" de gom nhieu tai san vao mot phieu.
--   2. Giu bang asset.asset_transfers hien co lam dong chi tiet tai san,
--      tranh pha vo API/service cu dang ghi theo tung asset_id.
--   3. Giữ bảng asset.asset_transfers hiện có làm dòng chi tiết tài sản,
--      tránh phá vỡ API/service cũ đang ghi theo từng asset_id 
--   3. Bổ sung bằng tài liệu/biên bản của phiên bàn giao. 
--   4. Bo sung bang xac nhan nhieu nguoi: nguoi ban giao, nguoi nhan,
--      quan ly, kho, ke toan... tuy luong nghiep vu.
--   5. Backfill moi dong transfer cu thanh mot phieu LEGACY rieng de du lieu cu
--      van doc duoc theo cau truc moi.
-- ============================================================================

CREATE SCHEMA IF NOT EXISTS asset;
-------------------------------------
-- Thông tin của 1 phiếu bàn giao
-- Một header chứa nhiều dòng tài sản trong asset_transfers
-- ---------------------------------------------------------------------------
-- PHIẾU BÀN GIAO TÀI SẢN
CREATE TABLE IF NOT EXISTS asset.asset_transfer_headers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transfer_code VARCHAR(60) NOT NULL,
    title VARCHAR(200) NULL,
    transfer_type VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',

    requested_by VARCHAR(200) NULL,
    requested_employee_id BIGINT NULL,
    approved_by VARCHAR(200) NULL,
    completed_by VARCHAR(200) NULL,
    cancelled_by VARCHAR(200) NULL,

    from_employee_id BIGINT NULL,
    to_employee_id BIGINT NULL,
    from_department_id BIGINT NULL,
    to_department_id BIGINT NULL,
    from_site_id BIGINT NULL,
    to_site_id BIGINT NULL,
    from_project_id BIGINT NULL,
    to_project_id BIGINT NULL,

    transfer_date DATE NULL,
    planned_handover_at TIMESTAMP NULL,
    completed_at TIMESTAMP NULL,
    cancelled_at TIMESTAMP NULL,
    cancel_reason VARCHAR(500) NULL,

    reason VARCHAR(1000) NULL,
    note VARCHAR(1000) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    updated_at TIMESTAMP NOT NULL DEFAULT now()
);

ALTER TABLE asset.asset_transfer_headers ADD COLUMN IF NOT EXISTS transfer_code VARCHAR(60);
ALTER TABLE asset.asset_transfer_headers ADD COLUMN IF NOT EXISTS title VARCHAR(200);
ALTER TABLE asset.asset_transfer_headers ADD COLUMN IF NOT EXISTS transfer_type VARCHAR(30);
ALTER TABLE asset.asset_transfer_headers ADD COLUMN IF NOT EXISTS status VARCHAR(30) NOT NULL DEFAULT 'DRAFT';
ALTER TABLE asset.asset_transfer_headers ADD COLUMN IF NOT EXISTS requested_by VARCHAR(200);
ALTER TABLE asset.asset_transfer_headers ADD COLUMN IF NOT EXISTS requested_employee_id BIGINT;
ALTER TABLE asset.asset_transfer_headers ADD COLUMN IF NOT EXISTS approved_by VARCHAR(200);
ALTER TABLE asset.asset_transfer_headers ADD COLUMN IF NOT EXISTS completed_by VARCHAR(200);
ALTER TABLE asset.asset_transfer_headers ADD COLUMN IF NOT EXISTS cancelled_by VARCHAR(200);
ALTER TABLE asset.asset_transfer_headers ADD COLUMN IF NOT EXISTS from_employee_id BIGINT;
ALTER TABLE asset.asset_transfer_headers ADD COLUMN IF NOT EXISTS to_employee_id BIGINT;
ALTER TABLE asset.asset_transfer_headers ADD COLUMN IF NOT EXISTS from_department_id BIGINT;
ALTER TABLE asset.asset_transfer_headers ADD COLUMN IF NOT EXISTS to_department_id BIGINT;
ALTER TABLE asset.asset_transfer_headers ADD COLUMN IF NOT EXISTS from_site_id BIGINT;
ALTER TABLE asset.asset_transfer_headers ADD COLUMN IF NOT EXISTS to_site_id BIGINT;
ALTER TABLE asset.asset_transfer_headers ADD COLUMN IF NOT EXISTS from_project_id BIGINT;
ALTER TABLE asset.asset_transfer_headers ADD COLUMN IF NOT EXISTS to_project_id BIGINT;
ALTER TABLE asset.asset_transfer_headers ADD COLUMN IF NOT EXISTS transfer_date DATE;
ALTER TABLE asset.asset_transfer_headers ADD COLUMN IF NOT EXISTS planned_handover_at TIMESTAMP;
ALTER TABLE asset.asset_transfer_headers ADD COLUMN IF NOT EXISTS completed_at TIMESTAMP;
ALTER TABLE asset.asset_transfer_headers ADD COLUMN IF NOT EXISTS cancelled_at TIMESTAMP;
ALTER TABLE asset.asset_transfer_headers ADD COLUMN IF NOT EXISTS cancel_reason VARCHAR(500);
ALTER TABLE asset.asset_transfer_headers ADD COLUMN IF NOT EXISTS reason VARCHAR(1000);
ALTER TABLE asset.asset_transfer_headers ADD COLUMN IF NOT EXISTS note VARCHAR(1000);
ALTER TABLE asset.asset_transfer_headers ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT now();
ALTER TABLE asset.asset_transfer_headers ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT now();

CREATE UNIQUE INDEX IF NOT EXISTS uk_asset_transfer_headers_transfer_code
    ON asset.asset_transfer_headers(transfer_code);
CREATE INDEX IF NOT EXISTS idx_asset_transfer_headers_status
    ON asset.asset_transfer_headers(status);
CREATE INDEX IF NOT EXISTS idx_asset_transfer_headers_transfer_type
    ON asset.asset_transfer_headers(transfer_type);
CREATE INDEX IF NOT EXISTS idx_asset_transfer_headers_transfer_date
    ON asset.asset_transfer_headers(transfer_date);
CREATE INDEX IF NOT EXISTS idx_asset_transfer_headers_requested_employee
    ON asset.asset_transfer_headers(requested_employee_id);
CREATE INDEX IF NOT EXISTS idx_asset_transfer_headers_to_employee
    ON asset.asset_transfer_headers(to_employee_id);
CREATE INDEX IF NOT EXISTS idx_asset_transfer_headers_to_department
    ON asset.asset_transfer_headers(to_department_id);
CREATE INDEX IF NOT EXISTS idx_asset_transfer_headers_to_site
    ON asset.asset_transfer_headers(to_site_id);

-- ---------------------------------------------------------------------------
-- Tài liệu/biên bản gắn với phiếu bàn giao. không gắn trực tiếp với 1 tài sản
-- Lưu metadata/object_key, file vật lý lưu ở MinIO
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS asset.asset_transfer_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transfer_header_id BIGINT NOT NULL,
    document_type VARCHAR(40) NOT NULL DEFAULT 'HANDOVER_MINUTES',
    document_status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    file_name VARCHAR(255) NOT NULL,
    object_key VARCHAR(500) NOT NULL,
    content_type VARCHAR(120) NULL,
    size_bytes BIGINT NULL,
    uploaded_by VARCHAR(200) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_asset_transfer_documents_object_key
    ON asset.asset_transfer_documents(object_key);
CREATE INDEX IF NOT EXISTS idx_asset_transfer_documents_header
    ON asset.asset_transfer_documents(transfer_header_id);
CREATE INDEX IF NOT EXISTS idx_asset_transfer_documents_type
    ON asset.asset_transfer_documents(document_type);

-- ---------------------------------------------------------------------------
-- Các bước xác nhận/ ký của bàn giao 
-- Moi dong la mot nguoi/vai tro can xac nhan: HANDOVER, RECEIVER, MANAGER...
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS asset.asset_transfer_confirmations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transfer_header_id BIGINT NOT NULL,
    confirmation_role VARCHAR(40) NOT NULL,
    confirmer_employee_id BIGINT NULL,
    confirmer_username VARCHAR(120) NULL,
    confirmer_name VARCHAR(200) NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    signature_method VARCHAR(30) NULL,
    signature_document_id BIGINT NULL,
    confirmed_at TIMESTAMP NULL,
    note VARCHAR(1000) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    updated_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_asset_transfer_confirmations_header
    ON asset.asset_transfer_confirmations(transfer_header_id);
CREATE INDEX IF NOT EXISTS idx_asset_transfer_confirmations_status
    ON asset.asset_transfer_confirmations(status);
CREATE INDEX IF NOT EXISTS idx_asset_transfer_confirmations_employee
    ON asset.asset_transfer_confirmations(confirmer_employee_id);
CREATE UNIQUE INDEX IF NOT EXISTS uk_asset_transfer_confirmations_unique_role
    ON asset.asset_transfer_confirmations(
        transfer_header_id,
        confirmation_role,
        COALESCE(confirmer_employee_id, -1),
        COALESCE(confirmer_username, '')
    );

-- ---------------------------------------------------------------------------
-- Mở rộng transfer cũ thành dòng chi tiết của 1 phiếu bàn giao
-- Nullable de service hien tai van chay duoc; backend moi se bat buoc gan header.
-- ---------------------------------------------------------------------------

ALTER TABLE asset.asset_transfers ADD COLUMN IF NOT EXISTS transfer_header_id BIGINT;
ALTER TABLE asset.asset_transfers ADD COLUMN IF NOT EXISTS line_no INTEGER;
ALTER TABLE asset.asset_transfers ADD COLUMN IF NOT EXISTS line_status VARCHAR(30) NOT NULL DEFAULT 'COMPLETED';
ALTER TABLE asset.asset_transfers ADD COLUMN IF NOT EXISTS status_before VARCHAR(30);
ALTER TABLE asset.asset_transfers ADD COLUMN IF NOT EXISTS status_after VARCHAR(30);
ALTER TABLE asset.asset_transfers ADD COLUMN IF NOT EXISTS book_value_at_transfer NUMERIC(18,2);
ALTER TABLE asset.asset_transfers ADD COLUMN IF NOT EXISTS receiver_note VARCHAR(1000);

CREATE INDEX IF NOT EXISTS idx_asset_transfers_transfer_header
    ON asset.asset_transfers(transfer_header_id);
CREATE INDEX IF NOT EXISTS idx_asset_transfers_line_status
    ON asset.asset_transfers(line_status);

-- ---------------------------------------------------------------------------
-- Constraints dat trong DO block de migration chay lai an toan tren DB da ton tai.
-- ---------------------------------------------------------------------------

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE connamespace = 'asset'::regnamespace
          AND conname = 'ck_asset_transfer_headers_status'
    ) THEN
    -- TRẠNG THÁI BÀN GIAO
        ALTER TABLE asset.asset_transfer_headers
            ADD CONSTRAINT ck_asset_transfer_headers_status
            CHECK (status IN (
                'DRAFT',
                'PENDING_CONFIRM',
                'PENDING_APPROVAL',
                'APPROVED',
                'COMPLETED',
                'REJECTED',
                'CANCELLED'
            )) NOT VALID;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE connamespace = 'asset'::regnamespace
          AND conname = 'ck_asset_transfer_headers_type'
    ) THEN
    -- CHECK RÀNG BUỘC TRẠNG THÁI PHIẾU ĐĂNG KÝ 
        ALTER TABLE asset.asset_transfer_headers
            ADD CONSTRAINT ck_asset_transfer_headers_type
            CHECK (transfer_type IN (
                'ASSIGN',
                'TRANSFER',
                'REVOKE',
                'REASSIGN',
                'BRANCH_TRANSFER',
                'DEPARTMENT_TRANSFER',
                'EMPLOYEE_TRANSFER',
                'PROJECT_TRANSFER',
                'WAREHOUSE_TRANSFER'
            )) NOT VALID;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE connamespace = 'asset'::regnamespace
          AND conname = 'fk_asset_transfer_documents_header'
    ) THEN
        ALTER TABLE asset.asset_transfer_documents
            ADD CONSTRAINT fk_asset_transfer_documents_header
            FOREIGN KEY (transfer_header_id)
            REFERENCES asset.asset_transfer_headers(id)
            ON DELETE CASCADE NOT VALID;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE connamespace = 'asset'::regnamespace
          AND conname = 'ck_asset_transfer_documents_type'
    ) THEN
        ALTER TABLE asset.asset_transfer_documents
            ADD CONSTRAINT ck_asset_transfer_documents_type
            CHECK (document_type IN (
                'HANDOVER_MINUTES',
                'SIGNED_MINUTES',
                'IMAGE',
                'ATTACHMENT',
                'OTHER'
            )) NOT VALID;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE connamespace = 'asset'::regnamespace
          AND conname = 'ck_asset_transfer_documents_status'
    ) THEN
        ALTER TABLE asset.asset_transfer_documents
            ADD CONSTRAINT ck_asset_transfer_documents_status
            CHECK (document_status IN ('ACTIVE', 'REVOKED')) NOT VALID;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE connamespace = 'asset'::regnamespace
          AND conname = 'ck_asset_transfer_documents_size_non_negative'
    ) THEN
        ALTER TABLE asset.asset_transfer_documents
            ADD CONSTRAINT ck_asset_transfer_documents_size_non_negative
            CHECK (size_bytes IS NULL OR size_bytes >= 0) NOT VALID;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE connamespace = 'asset'::regnamespace
          AND conname = 'fk_asset_transfer_confirmations_header'
    ) THEN
        ALTER TABLE asset.asset_transfer_confirmations
            ADD CONSTRAINT fk_asset_transfer_confirmations_header
            FOREIGN KEY (transfer_header_id)
            REFERENCES asset.asset_transfer_headers(id)
            ON DELETE CASCADE NOT VALID;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE connamespace = 'asset'::regnamespace
          AND conname = 'fk_asset_transfer_confirmations_signature_document'
    ) THEN
        ALTER TABLE asset.asset_transfer_confirmations
            ADD CONSTRAINT fk_asset_transfer_confirmations_signature_document
            FOREIGN KEY (signature_document_id)
            REFERENCES asset.asset_transfer_documents(id)
            ON DELETE SET NULL NOT VALID;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE connamespace = 'asset'::regnamespace
          AND conname = 'ck_asset_transfer_confirmations_role'
    ) THEN
        ALTER TABLE asset.asset_transfer_confirmations
            ADD CONSTRAINT ck_asset_transfer_confirmations_role
            CHECK (confirmation_role IN (
                'REQUESTER',
                'HANDOVER',
                'RECEIVER',
                'MANAGER',
                'WAREHOUSE',
                'ACCOUNTING',
                'ADMIN'
            )) NOT VALID;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE connamespace = 'asset'::regnamespace
          AND conname = 'ck_asset_transfer_confirmations_status'
    ) THEN
        ALTER TABLE asset.asset_transfer_confirmations
            ADD CONSTRAINT ck_asset_transfer_confirmations_status
            CHECK (status IN (
                'PENDING',
                'APPROVED',
                'REJECTED',
                'CANCELLED',
                'SKIPPED'
            )) NOT VALID;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE connamespace = 'asset'::regnamespace
          AND conname = 'fk_asset_transfers_header'
    ) THEN
        ALTER TABLE asset.asset_transfers
            ADD CONSTRAINT fk_asset_transfers_header
            FOREIGN KEY (transfer_header_id)
            REFERENCES asset.asset_transfer_headers(id)
            ON DELETE CASCADE NOT VALID;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE connamespace = 'asset'::regnamespace
          AND conname = 'ck_asset_transfers_line_status'
    ) THEN
        ALTER TABLE asset.asset_transfers
            ADD CONSTRAINT ck_asset_transfers_line_status
            CHECK (line_status IN (
                'PENDING',
                'APPROVED',
                'COMPLETED',
                'REJECTED',
                'CANCELLED'
            )) NOT VALID;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE connamespace = 'asset'::regnamespace
          AND conname = 'ck_asset_transfers_book_value_non_negative'
    ) THEN
        ALTER TABLE asset.asset_transfers
            ADD CONSTRAINT ck_asset_transfers_book_value_non_negative
            CHECK (book_value_at_transfer IS NULL OR book_value_at_transfer >= 0) NOT VALID;
    END IF;
END $$;

-- ---------------------------------------------------------------------------
-- Backfill du lieu cu: moi transfer cu thanh mot phieu LEGACY rieng.
-- Backend moi co the gom nhieu dong vao cung transfer_header_id.
-- ---------------------------------------------------------------------------

INSERT INTO asset.asset_transfer_headers (
    transfer_code,
    title,
    transfer_type,
    status,
    requested_by,
    approved_by,
    from_employee_id,
    to_employee_id,
    from_department_id,
    to_department_id,
    from_site_id,
    to_site_id,
    from_project_id,
    to_project_id,
    transfer_date,
    completed_at,
    reason,
    created_at,
    updated_at
)
SELECT
    'LEGACY-' || t.id,
    'Phieu ban giao tao tu du lieu cu #' || t.id,
    t.transfer_type,
    'COMPLETED',
    t.performed_by,
    t.approved_by,
    t.from_employee_id,
    t.to_employee_id,
    t.from_department_id,
    t.to_department_id,
    t.from_site_id,
    t.to_site_id,
    t.from_project_id,
    t.to_project_id,
    t.transfer_date,
    COALESCE(t.created_at, now()),
    t.reason,
    COALESCE(t.created_at, now()),
    now()
FROM asset.asset_transfers t
WHERE t.transfer_header_id IS NULL
  AND NOT EXISTS (
      SELECT 1
      FROM asset.asset_transfer_headers h
      WHERE h.transfer_code = 'LEGACY-' || t.id
  );

UPDATE asset.asset_transfers t
SET transfer_header_id = h.id,
    line_no = COALESCE(t.line_no, 1),
    line_status = COALESCE(t.line_status, 'COMPLETED')
FROM asset.asset_transfer_headers h
WHERE t.transfer_header_id IS NULL
  AND h.transfer_code = 'LEGACY-' || t.id;

COMMENT ON TABLE asset.asset_transfer_headers IS
    'Header/phieu ban giao tai san. Mot phieu co the gom nhieu dong asset_transfers.';
COMMENT ON TABLE asset.asset_transfer_documents IS
    'Tai lieu va bien ban cua phieu ban giao, luu metadata file/object_key MinIO.';
COMMENT ON TABLE asset.asset_transfer_confirmations IS
    'Cac buoc xac nhan/ky cua phieu ban giao theo vai tro va nguoi xac nhan.';
COMMENT ON COLUMN asset.asset_transfers.transfer_header_id IS
    'Lien ket dong transfer cu voi header phieu ban giao moi.';
