-- ============================================================================
-- V8 - Danh muc dinh nghia audit log.
--
-- Muc tieu:
--   1. Tao bang metadata de admin quan ly module/entity_type/action cua log.
--   2. Ho tro UI hien thi ten tieng Viet, mo ta, muc do nghiem trong, thu tu.
--   3. KHONG tao khoa ngoai tu audit_logs sang bang nay.
--
-- Ly do khong dung FK:
--   - Audit log la du lieu lich su, khong duoc fail chi vi thieu metadata.
--   - Action moi co the duoc backend ghi truoc, admin bo sung ten hien thi sau.
--   - Doi ten hien thi khong lam thay doi ban ghi audit cu.
--
-- Quy uoc JSON trong asset.audit_logs:
--   before_data:
--     Object snapshot truoc thao tac. Key la ten field nghiep vu.
--     Vi du: {"assignedEmployeeId": 1, "status": "ASSIGNED"}
--
--   after_data:
--     Object snapshot sau thao tac. Key giong before_data.
--     Vi du: {"assignedEmployeeId": 2, "status": "ASSIGNED"}
--
--   changed_fields:
--     Object gom cac field co thay doi.
--     Moi field co cau truc {"before": <old>, "after": <new>}.
--     Vi du:
--     {
--       "assignedEmployeeId": {"before": 1, "after": 2},
--       "departmentId": {"before": 10, "after": 20}
--     }
--
-- DB khong check schema JSONB de giu audit linh hoat cho cac nghiep vu moi.
-- ============================================================================

CREATE SCHEMA IF NOT EXISTS asset;

CREATE TABLE IF NOT EXISTS asset.audit_log_definitions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module VARCHAR(50) NOT NULL,
    entity_type VARCHAR(80) NOT NULL,
    action VARCHAR(50) NOT NULL,
    display_name VARCHAR(200) NOT NULL,
    description VARCHAR(1000) NULL,
    default_severity VARCHAR(20) NOT NULL DEFAULT 'INFO',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    updated_at TIMESTAMP NOT NULL DEFAULT now(),
    CONSTRAINT uk_audit_log_definitions_key UNIQUE (module, entity_type, action),
    CONSTRAINT ck_audit_log_definitions_severity
        CHECK (default_severity IN ('INFO', 'WARNING', 'CRITICAL'))
);

CREATE INDEX IF NOT EXISTS idx_audit_log_definitions_module
    ON asset.audit_log_definitions(module);
CREATE INDEX IF NOT EXISTS idx_audit_log_definitions_entity_type
    ON asset.audit_log_definitions(entity_type);
CREATE INDEX IF NOT EXISTS idx_audit_log_definitions_action
    ON asset.audit_log_definitions(action);
CREATE INDEX IF NOT EXISTS idx_audit_log_definitions_active
    ON asset.audit_log_definitions(is_active);

INSERT INTO asset.audit_log_definitions (
    module,
    entity_type,
    action,
    display_name,
    description,
    default_severity,
    sort_order
)
VALUES
    (
        'ASSET_TRANSFER',
        'ASSET',
        'TRANSFER_CREATED',
        'Tạo bản ghi bàn giao tài sản',
        'Tài sản được đưa vào một bản ghi hoặc phiếu bàn giao.',
        'INFO',
        10
    ),
    (
        'ASSET_TRANSFER',
        'ASSET',
        'TRANSFER_APPLIED',
        'Áp dụng bàn giao vào tài sản',
        'Thông tin người giữ, phòng ban, chi nhánh, dự án hoặc trạng thái tài sản đã được cập nhật sau bàn giao.',
        'INFO',
        20
    ),
    (
        'ASSET_TRANSFER',
        'ASSET_TRANSFER',
        'TRANSFER_CREATED',
        'Tạo dòng bàn giao',
        'Tạo dòng chi tiết bàn giao/luân chuyển cho một tài sản.',
        'INFO',
        30
    ),
    (
        'ASSET_TRANSFER',
        'ASSET_TRANSFER',
        'TRANSFER_DELETED',
        'Xóa dòng bàn giao',
        'Xóa bản ghi bàn giao/luân chuyển legacy hoặc dòng chi tiết bàn giao.',
        'WARNING',
        40
    ),
    (
        'ASSET_TRANSFER',
        'ASSET_TRANSFER_HEADER',
        'TRANSFER_DRAFT_CREATED',
        'Tạo phiếu bàn giao nháp',
        'Tạo phiếu bàn giao ở trạng thái nháp.',
        'INFO',
        50
    ),
    (
        'ASSET_TRANSFER',
        'ASSET_TRANSFER_HEADER',
        'TRANSFER_SUBMITTED',
        'Gửi phiếu bàn giao để xác nhận',
        'Phiếu bàn giao được gửi đến các bên liên quan để xác nhận.',
        'INFO',
        60
    ),
    (
        'ASSET_TRANSFER',
        'ASSET_TRANSFER_HEADER',
        'TRANSFER_CONFIRM_APPROVED',
        'Xác nhận đồng ý phiếu bàn giao',
        'Một người hoặc vai trò liên quan đã xác nhận đồng ý phiếu bàn giao.',
        'INFO',
        70
    ),
    (
        'ASSET_TRANSFER',
        'ASSET_TRANSFER_HEADER',
        'TRANSFER_CONFIRM_REJECTED',
        'Từ chối xác nhận phiếu bàn giao',
        'Một người hoặc vai trò liên quan đã từ chối xác nhận phiếu bàn giao.',
        'WARNING',
        80
    ),
    (
        'ASSET_TRANSFER',
        'ASSET_TRANSFER_HEADER',
        'TRANSFER_APPROVED',
        'Duyệt phiếu bàn giao',
        'Phiếu bàn giao đã được người có quyền duyệt.',
        'INFO',
        90
    ),
    (
        'ASSET_TRANSFER',
        'ASSET_TRANSFER_HEADER',
        'TRANSFER_COMPLETED',
        'Hoàn tất phiếu bàn giao',
        'Phiếu bàn giao đã hoàn tất và thông tin tài sản đã được cập nhật.',
        'INFO',
        100
    ),
    (
        'ASSET_TRANSFER',
        'ASSET_TRANSFER_HEADER',
        'TRANSFER_CANCELLED',
        'Hủy phiếu bàn giao',
        'Phiếu bàn giao bị hủy trước khi hoàn tất.',
        'WARNING',
        110
    ),
    (
        'ASSET_TRANSFER',
        'ASSET_TRANSFER_HEADER',
        'TRANSFER_DOCUMENT_ADDED',
        'Thêm biên bản/tài liệu bàn giao',
        'Một tài liệu hoặc biên bản đã được gắn vào phiếu bàn giao.',
        'INFO',
        120
    )
ON CONFLICT (module, entity_type, action) DO UPDATE
SET display_name = EXCLUDED.display_name,
    description = EXCLUDED.description,
    default_severity = EXCLUDED.default_severity,
    sort_order = EXCLUDED.sort_order,
    updated_at = now();

COMMENT ON TABLE asset.audit_log_definitions IS
    'Danh muc metadata cua audit log, dung de hien thi/loc log. Khong FK tu audit_logs de tranh ghi log bi fail khi thieu metadata.';
COMMENT ON COLUMN asset.audit_log_definitions.module IS
    'Nhom nghiep vu ghi log, vi du ASSET_TRANSFER, ASSET, BOOKING.';
COMMENT ON COLUMN asset.audit_log_definitions.entity_type IS
    'Loai doi tuong cua audit_logs.entity_type.';
COMMENT ON COLUMN asset.audit_log_definitions.action IS
    'Ma hanh dong cua audit_logs.action.';
