spring:
  application:
    name: asset-service
  datasource:
    url: jdbc:postgresql://localhost:5432/bimlab?currentSchema=asset
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      max-lifetime: ${SPRING_DATASOURCE_HIKARI_MAX_LIFETIME:120000}
      idle-timeout: ${SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT:60000}
      minimum-idle: ${SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE:1}
      maximum-pool-size: ${SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE:5}
      keepalive-time: ${SPRING_DATASOURCE_HIKARI_KEEPALIVE_TIME:30000}
      validation-timeout: ${SPRING_DATASOURCE_HIKARI_VALIDATION_TIMEOUT:5000}
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        default_schema: asset
        hbm2ddl:
          create_namespaces: true

server:
  port: 8086
  error:
    include-message: always
    include-binding-errors: never
    include-stacktrace: never

app:
  jwt:
    secret: ${APP_JWT_SECRET}
    rsa-public-key: ${RSA_PUBLIC_KEY:}
  auth-service:
    url: ${AUTH_SERVICE_URL:http://localhost:8081}

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never
